#!/bin/bash
# Periodic Apex feed-port scan: discover karting circuits that are live right now
# and add the newly-named ones to tracks.db. Restarts the backend when new tracks
# were added, but at most once an hour so frequent scans don't thrash live data
# collection. Intended to run from cron — see the crontab entry alongside it.
#
#   crontab:  */15 * * * * /home/ubuntu/LT-Analyzer/scripts/cron_apex_scan.sh
RESTART_MIN_GAP=3300   # don't restart the backend more than once per ~55 min
set -u
cd /home/ubuntu/LT-Analyzer || exit 1
PY=./racing-venv/bin/python
LOG=logs/apex_scan.log
mkdir -p logs

ts() { date '+%Y-%m-%d %H:%M:%S'; }

before=$(sqlite3 tracks.db "SELECT COUNT(*) FROM tracks;" 2>/dev/null || echo 0)
echo "[$(ts)] scan start (tracks=$before)" >> "$LOG"

# --known-only: only add circuits we have a real config venue name for
# (apex_known_tracks.json, generated by discover_apex_tracks.py). Generic
# layout-only feeds are scanned/logged but NOT added, so deleted generics stay
# deleted. To add a new unknown circuit, add its slug to the discoverer and
# regenerate apex_known_tracks.json.
"$PY" scripts/scan_apex_ports.py --start 6900 --end 9999 --concurrency 60 \
      --names-from apex_known_tracks.json --apply --known-only >> "$LOG" 2>&1

after=$(sqlite3 tracks.db "SELECT COUNT(*) FROM tracks;" 2>/dev/null || echo "$before")
added=$(( after - before ))
echo "[$(ts)] scan done (tracks=$after, +$added)" >> "$LOG"

if [ "$added" -gt 0 ]; then
    marker=logs/.last_restart
    if [ -f "$marker" ] && [ $(( $(date +%s) - $(stat -c %Y "$marker") )) -lt "$RESTART_MIN_GAP" ]; then
        echo "[$(ts)] +$added new, but backend restarted <55m ago — deferring to next window" >> "$LOG"
    else
        echo "[$(ts)] +$added new track(s) — restarting backend to monitor them" >> "$LOG"
        pm2 restart lt-analyzer-backend >> "$LOG" 2>&1
        touch "$marker"
    fi
fi
